### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by R3nierjvr** [custom-cards/text-element#4]
please could you update this, as this no longer works

**Comment by ludeeus** [comment]
What does not work? How does it not work? 
_Pro tip: "this no longer works" / "does not work" are the worst posible issues opened on GitHub, they have **no** context, and will only take longer to resolve then if you where to open a meaning full issue, with logs/screenshots/proper description._

**Comment by R3nierjvr** [comment]
My apologies, since 0.80 update a lot of the custom:cards stopped working they later fixed this but cards need to be updated. not sure how this is beyond me. But to to get down to basics is that even if I add this as a resource the error that **custom:text-element does not exist** comes up. Fair enough this was my first time linking a custom card as a resource. So to check if it was not something done on my side I added another custom card, "Monster card". This work perfectly no issues so not a dependency issue or a browsers issue because I tested this on four browsers.
Here mu ui-lovelace.yaml file. I have now switched back to build in and used resources there like monster cards there with no issue

title: HomeServer
resources:
  - url: /local/text-element.js?v=0
    type: js
views:
  - title: Overview
    cards:
    - type: picture-elements 
      image: /local/plexbanner.jpeg   
      elements:        
        - type: custom:text-element
          text: "<b style='color: orange; font-size: 16px'>Total </b>"
        - type: state-label
          entity: sensor.plex
          style: {color: white, font-size: 16px, left: 20%, top: 26%}

**Comment by R3nierjvr** [comment]
this is the guide I was using when i found the custom:text element my yaml file is also linked with the query at the bottom : https://community.home-assistant.io/t/how-to-convert-kb-s-to-mbps-in-a-sensor-template/109420/7

and heres a link with simmiliar issues : https://github.com/custom-cards/button-card/issues/43

**Comment by ludeeus** [comment]
There is nothing to fix in this card, it still works.
Open dev console in your browser, then reload the page and look for errors there.
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#browser-console
You can also try changing `?v=0` to `?v=1`

**Comment by R3nierjvr** [comment]
Ok will try tonight, my apologies, will let you know

**Comment by R3nierjvr** [comment]
Ok Just tried it, and what a really hate is that I was wrong. Your plugin is 100% working. 
My sincere apologies. Turned out to be a stupid fault on my end ...I did not download the raw version. Step to on the troubleshooting. You my friend deserve a stiff drink for putting up with me. Thank you.
