### ISSUE TITLE
Add background for element card - Plex

### ISSUE THREAD

**Issue by EroticD** [custom-cards/text-element#5]
**Is your feature request related to a problem? Please describe.**
There is an example output of what to expect, but no actual background to utilize.

**Describe the solution you'd like**
Add background to repo.

**Describe alternatives you've considered**
Creating own repo with background image, which is of no use to others.

**Additional context**
Link to background file: https://i.imgur.com/9Bsk9ab.png
also attached. 

![plex](https://user-images.githubusercontent.com/12676250/77788620-e1c2cc80-7061-11ea-940e-a2cece02ed8d.png)

**Comment by ludeeus** [comment]
The image is in the README, just save if you really want to use that one.
